220 server documentation
Zenika/feedzback pull request #225
Opened 2022-08-17 13:50 UTC by bnyat22

Documentation pour le coté serveur

![Screenshot 2022-08-17 at 15 49 22](https://user-images.githubusercontent.com/47147025/185151012-f5aece33-100e-4046-89ce-bd8dd410bced.png)

2022-08-17 14:04 UTC, merged

2022-08-18 08:23 UTC, patou requested changes
Il faut pas mettre le résultat de la jsdoc dans le repos git car il ne sera pas à jours. Par contre tu peut faire un jobs qui le build et le deploy automatiquement sur github pages.

2022-08-18 08:58 UTC, bnyat22 commented
> Il faut pas mettre le résultat de la jsdoc dans le repos git car il ne sera pas à jours. Par contre tu peut faire un jobs qui le build et le deploy automatiquement sur github pages.

> quand tu dis GitHub pages tu veux dire le wiki?

2022-08-18 19:00 UTC, patou commented
> > Il faut pas mettre le résultat de la jsdoc dans le repos git car il ne sera pas à jours. Par contre tu peut faire un jobs qui le build et le deploy automatiquement sur github pages.
> 
> > quand tu dis GitHub pages tu veux dire le wiki?

Non je dis github pages ...

2022-08-19 08:01 UTC, bnyat22 commented
> > > Il faut pas mettre le résultat de la jsdoc dans le repos git car il ne sera pas à jours. Par contre tu peut faire un jobs qui le build et le deploy automatiquement sur github pages.
> > 
> > 
> > > quand tu dis GitHub pages tu veux dire le wiki?
> 
> Non je dis github pages ...

> oki ça marche