Update README.md
Zenika/feedzback pull request #244
Opened 2023-07-21 13:18 UTC by bnyat22

2023-07-21 13:37 UTC, Tarektouati requested changes
J’ai mis quelques commentaires sur la forme et quelques typo dans le doc.

2023-07-21 13:37 UTC, Tarektouati commented on README.md
> +    `DatastoreApi` yout endpoint datastore in order to simulate it in local
```suggestion
    `DatastoreApi` your local datastore endpoint in order to simulate it in local
```

2023-07-21 13:37 UTC, Tarektouati commented on README.md
> +  setp 1: download it in your local
```suggestion
  step 1: download the Firebase simulator
```
 Ça serait cool de rajouter l’URL de la documentation Firebase ici

2023-07-21 13:37 UTC, Tarektouati commented on README.md
> +  gcloud components install cloud-datastore-emulator
```suggestion
in your shell run `gcloud components install cloud-datastore-emulator`
```

2023-07-21 13:37 UTC, Tarektouati commented on README.md
> +  gcloud beta emulators datastore start
```suggestion
  step 2: start the Firebase simulator
  in your shell run `gcloud beta emulators datastore start`
```

2023-07-21 13:41 UTC, bnyat22 commented on README.md
> +  gcloud beta emulators datastore start
on utilise datastore emulator

2023-07-28 13:25 UTC, VincentLandais requested changes

2023-07-28 13:25 UTC, VincentLandais commented on README.md
> +    `MAILGUN_DOMAIN`= your mailgun domain
Faudrait faire les modifs dans le code et dans le app.yaml du coup aussi

2024-01-08 05:45 UTC, closed without merging