A lot of stuff
Zenika/feedzback pull request #261
Opened 2023-10-25 15:13 UTC by avine

- start cleaning package.json
- prevent access to login page when already logged in
- improve design of auth service and auth guard
- move header and footer to dedicated components
- and some other minor things...

2023-10-27 14:19 UTC, VincentLandais approved these changes

2023-11-14 14:51 UTC, patou requested changes
Sincèrement, une PR avec 63 commit, 
![image](https://github.com/Zenika/feedzback/assets/841858/dc08caa2-1616-4e8d-99d0-d2e642ca40b5)
Et des modifications dans tous les sens, ce n'est pas du travail en équipe.
Impossible de faire une review, et savoir ce qui a changé, de discuter des changements.
J'appelle plus ça des minors things !

2023-11-14 18:37 UTC, avine commented
> Sincèrement, une PR avec 63 commit, ![image](https://user-images.githubusercontent.com/841858/282814776-dc08caa2-1616-4e8d-99d0-d2e642ca40b5.png) Et des modifications dans tous les sens, ce n'est pas du travail en équipe. Impossible de faire une review, et savoir ce qui a changé, de discuter des changements. J'appelle plus ça des minors things !

Hello Patrice,

Je comprends ta réaction.
Je te donne quelques infos supplémentaires pour contextualiser ces changements.

Compte tenu du fait que l'app était en Angular 13 (donc un peu vieillissante), que Bnyat n'a que les vendredi après-midi pour travailler dessus, qu'il y a pas de trous dans la raquette côté backend (je reviens sur ce point juste après...) et que Mehdi et moi-même somment en interco et avons été embarqué full-time sur cette app ; nous avons décidé de partir sur une V2.

Côté front : 
- toujours Angular (mais en v16)
- Angular Material pour les composants UI (ça fit bien le besoin - faudrait une démo pour te montrer ça...)

Côté back : 
- on hésite encore (perso, je propose NestJS)
- REST au lieu de GraphQL pas nécessaire dans ce contexte métier

Les trous dans la raquette côté back ->  aujourd'hui en prod on peut :
- voir les feedbacks de tous le monde (faut juste envoyer la bonne requête GraphQL)
- faire une usurpation d'identité et faire croire que A a envoyé un feedback à B

Ce que je propose : 
- A la demande de feedback, on crée un feedback "vide" en base : 

```json
{ 
  "id": "123AZERTY", 
  "senderEmail": "A@gmail.com", 
  "receiverEmail": "B@zenika.com", 
  "status": "ask" 
}
```

- Pour accéder au formulaire un lien du genre : 

```txt
https://feedzback.zenika.com/send?token=123AZERTY
```

A l'envoi du formulaire (uniquement les champs `positiveFeedback`, `toImprove`, `comment` et le `token`) on obtient en base :

```json
{ 
  "id": "123AZERTY", 
  "senderEmail": "A@gmail.com", 
  "receiverEmail": "B@zenika.com", 
  "status": "done", 
  "positiveFeedback": "OK", 
  "toImprove": "KO" ,
  "comment": "blabla"
}
```

Ainsi, on a bien un `token` a usage unique permettant à A de faire un feedback à B comme demandé initialement par B.

2023-11-15 15:18 UTC, patou commented
> > Sincèrement, une PR avec 63 commit, 
> > 
> > ![image](https://user-images.githubusercontent.com/841858/282814776-dc08caa2-1616-4e8d-99d0-d2e642ca40b5.png)
> > 
> >  Et des modifications dans tous les sens, ce n'est pas du travail en équipe. Impossible de faire une review, et savoir ce qui a changé, de discuter des changements. J'appelle plus ça des minors things !
> 
> Hello Patrice,
> 
> Je comprends ta réaction. Je te donne quelques infos supplémentaires pour contextualiser ces changements.
> 
> Compte tenu du fait que l'app était en Angular 13 (donc un peu vieillissante), que Bnyat n'a que les vendredi après-midi pour travailler dessus, qu'il y a pas de trous dans la raquette côté backend (je reviens sur ce point juste après...) et que Mehdi et moi-même somment en interco et avons été embarqué full-time sur cette app ; nous avons décidé de partir sur une V2.
> 
> Côté front :
> 
> *   toujours Angular (mais en v16)
> *   Angular Material pour les composants UI (ça fit bien le besoin - faudrait une démo pour te montrer ça...)
> 
> Côté back :
> 
> *   on hésite encore (perso, je propose NestJS)
> *   REST au lieu de GraphQL pas nécessaire dans ce contexte métier
> 
> Les trous dans la raquette côté back -> aujourd'hui en prod on peut :
> 
> *   voir les feedbacks de tous le monde (faut juste envoyer la bonne requête GraphQL)
> *   faire une usurpation d'identité et faire croire que A a envoyé un feedback à B
> 
> Ce que je propose :
> 
> *   A la demande de feedback, on crée un feedback "vide" en base :
> 
> ```json
> { 
>   "id": "123AZERTY", 
>   "senderEmail": "A@gmail.com", 
>   "receiverEmail": "B@zenika.com", 
>   "status": "ask" 
> }
> ```
> 
> *   Pour accéder au formulaire un lien du genre :
> 
> ```
> https://feedzback.zenika.com/send?token=123AZERTY
> ```
> 
> A l'envoi du formulaire (uniquement les champs `positiveFeedback`, `toImprove`, `comment` et le `token`) on obtient en base :
> 
> ```json
> { 
>   "id": "123AZERTY", 
>   "senderEmail": "A@gmail.com", 
>   "receiverEmail": "B@zenika.com", 
>   "status": "done", 
>   "positiveFeedback": "OK", 
>   "toImprove": "KO" ,
>   "comment": "blabla"
> }
> ```
> 
> Ainsi, on a bien un `token` a usage unique permettant à A de faire un feedback à B comme demandé initialement par B.
> 
> Statut : La V2 du front est casi terminée (y a une démo ce jeudi) ; côté back c'est à l'étude.

Je comprends sur la nécessité de faire avancer les choses.  
Simple, vous pouvez créer une branche, develop (ou v2), puis faire des PR pour chaque sujet que vous merger ensuite sur cette branche.  
Et une fois toutes les modifications faites faire un merge vers la branche main pour mettre en production

2024-01-08 05:43 UTC, closed without merging