Email autocomplete from dev
Zenika/feedzback pull request #291
Opened 2024-01-08 14:31 UTC by NorbertPointu

Add autocompelete

Issue : 
When the autocomplete is displaying we see the back screen :
![image](https://github.com/Zenika/feedzback/assets/62135994/c47ac504-5743-4d6d-9001-1b9aa8b8de15)

When we select an item, the input selection is not cleared

2024-01-09 13:14 UTC, avine requested changes

2024-01-10 10:19 UTC, NorbertPointu commented on server/src/feedback/feedback.dto.ts
> +  @ApiProperty({ description: 'message' })
Move to be the first decorator in all places

2024-01-10 10:20 UTC, NorbertPointu commented on server/src/employee/employee.controller.ts
> +@ApiBearerAuth('defaultBearerAuth')
le nom "defaultBearerAuth"  a été supprimé

2024-01-10 10:21 UTC, NorbertPointu commented on server/src/employee/employee.controller.ts
> +    return this.employeeDbService.searchEmployee(searchInput);
already changed

2024-01-10 10:22 UTC, NorbertPointu commented on server/src/employee/employee-db/employee-db.service.ts
> +      displayName: names?.[0].displayName ?? 'Not defined',
will be changed when the api will be on

2024-01-10 10:26 UTC, NorbertPointu commented on server/src/core/auth/auth.service.ts
> +
done, add format on save in my vscode

2024-01-15 08:19 UTC, closed without merging