Draft: Create and schedule a daily feedzback usage export
Zenika/feedzback pull request #416
Opened 2024-03-04 15:45 UTC by noancloarec

2024-03-08 15:45 UTC, lisequesnel commented on usage_analytics/Readme.md
> +- Have gcloud installed and a project owner accout
```suggestion
- Have gcloud installed and a project owner account
```

2024-03-12 22:09 UTC, avine requested changes

2024-03-12 22:09 UTC, avine commented on .circleci/README.md
Is the analytics related to `CircleCI` ?
If not, you can discard this change.

otherwise, note that this file has been moved to: 
https://github.com/Zenika/feedzback/blob/main/docs-source/docs/ci-cd/circle-ci.md

2024-03-12 22:18 UTC, avine commented on usage_analytics/Readme.md
Can we rename the folder name with "`-`" instead of "`_`" ? 
- `usage-analytics`
- `create-analytics`

2024-03-12 22:21 UTC, avine commented on usage_analytics/Readme.md
Is it relevant to move this README to the new dos build with Docusaurus?

The file localtion could be : 
https://github.com/Zenika/feedzback/blob/main/docs-source/docs/usage-analytics.md

You should also reference the new file in the sidebar:
https://github.com/Zenika/feedzback/blob/main/docs-source/sidebars.ts

2024-03-12 22:24 UTC, avine commented on usage_analytics/Readme.md
But leave it in place for now...
You will create a new PR to move the README to Docusaurus after merging this one.

2024-03-15 09:14 UTC, avine approved these changes

2024-03-15 09:20 UTC, noancloarec commented on .circleci/config.yml
> +      ### Finally deploy the cloud functions for analytics purposes.
Suggéré par @avine
```suggestion
      ### Deploy the cloud functions for analytics purposes.
```

2024-03-15 09:20 UTC, noancloarec commented on .circleci/config.yml
> +      ### Finally deploy the cloud functions for analytics purposes.
Suggéré par @avine
```suggestion
      ### Deploy the cloud functions for analytics purposes.
```

2024-03-15 09:20 UTC, noancloarec commented on .circleci/config.yml
> +      ### Finally deploy the cloud functions for analytics purposes.
Suggéré par @avine
```suggestion
      ### Deploy the cloud functions for analytics purposes.
```

2024-03-15 11:18 UTC, merged