48 solliciter un feedback
Zenika/feedzback pull request #49
Opened 2022-05-06 14:42 UTC by bnyat22

2022-05-09 08:37 UTC, patou requested changes

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.css
> +    border-color: #ccc !important;
pourquoi tu es obligé de mettre un !important ?
C'est pas une bonne pratique d'accessibilité.
https://uxengineer.com/css-specificity-avoid-important-css/

Il faut que tu es une regle plus précise que celle que tu essaye de modifier
(ou si dans ton cas c'est les deux border-color en dessous, il faut donc que ce code soit après les lignes).

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.css
> +    }
Ton code css n'est pas bien formaté.

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.html
> +                <label class="col-2">Collégue Email:</label>
```suggestion
                <label class="col-2">Email du ton collègue:</label>
```

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.html
> +                <input  type="text" id="senderEmail" name="senderEmail"  [(ngModel)]="askFeedbackRequest.senderEmail" required class="col-6 form-control required" #senderEmail="ngModel" placeholder="
```suggestion
                <input  type="text" id="senderEmail" name="senderEmail"  [(ngModel)]="askFeedbackRequest.senderEmail" required class="col-6 form-control required" #senderEmail="ngModel" placeholder="Ex: marie.mettrand@example.com"/>
```

C'est pas une bonne pratique de mettre un vrai email, on sait jamais si cette email n'existe pas !

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.html
> +                <input type="text" id="email" name="email" [(ngModel)]="askFeedbackRequest.email"  class="col-6 form-control required" #email="ngModel" required placeholder="Ex: pierre.pompidor@gmail
```suggestion
                <input type="text" id="email" name="email" [(ngModel)]="askFeedbackRequest.email"  class="col-6 form-control required" #email="ngModel" required placeholder="Ex: pierre.pompidor@example.com"/>
```
C'est pas une bonne pratique de mettre un vrai email, on sait jamais si cette email n'existe pas !

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.spec.ts
> +    ]
idem pb de formatage.

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.ts
> +  sendFeedbackRequest(email:$email, senderEmail:$senderEmail, text:$text)
Utilise des nom de parametres plus précis que juste text ou email dont on ne sait pas ce que ça veut dire.

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.ts
> +      data.data.sendFeedbackRequest==='Votre demande a bien été envoyé'? this.router.navigate(['/demandeEnvoye']):this.err=data.data.sendFeedbackRequest
Oula,

Tu fait une affectation de variable dans data.data.sendFeebackRequest ! je ne voit pas où ce trouve cette variable data qui contient data (déjà un il y a un problème de nommage, on devrait pas avoir un data impriqué dans un data.

Mais surtout tu met dans cette variable une expression binaire qui fait soit un navigate soit une autre affectation.

Un if else serait plus clair.

2022-05-09 08:37 UTC, patou commented on client/src/app/feedback-envoye/feedback-envoye.component.ts
> +  }
Si tu fait rien dans le ngOnInit, il n'est pas nécessaire de le mettre.

2022-05-09 08:37 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    console.log(JSON.stringify(activateRouter.snapshot.paramMap))
console.log a supprimé.

2022-05-09 08:37 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    console.log("heyyyy")
Idem, on essaye de ne pas garder du code de debug.

2022-05-09 08:37 UTC, patou commented on server/index.js
> +
Que fait ce code ici ?
Cela semble être un test.

2022-05-09 08:37 UTC, patou commented on server/src/emailTemplate/askFeedbackModel.html
> +      <p>Votre collègue {{senderName}}  vous demande de lui envoyer un feedzback!</p>
```suggestion
      <p>Votre collègue {{senderName}} vous demande de lui envoyer un feedzback!</p>
```

2022-05-09 08:37 UTC, patou commented on server/src/emailTemplate/askFeedbackModel.html
> +        <p>Cliquez le lien dessous pour lui envoyer le feedback souhaté!</p>
```suggestion
        <p>Cliquez sur le lien ci-dessous pour lui envoyer le feedback souhaité!</p>
```

2022-05-09 08:37 UTC, patou commented on server/src/graphql/typeDefs.js
>      createMessage(email:String!,message:SendRequest!):String
Il faudra renommer le createMessage, pour lui donner le sens fonctionnel (envoyer un feedzback)

2022-05-09 08:37 UTC, patou commented on server/src/model/feedbackRequestTemplate.js
> +    }).join('');
il y a des lib pour faire du templating qui sera plus sécurisé que de le faire à la main. (Ici tu as une faille xss https://fr.wikipedia.org/wiki/Cross-site_scripting)

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-envoye/demande-envoye.component.spec.ts
> +});
Si le test ne fait rien, autant rien mettre.

2022-05-09 08:37 UTC, patou commented on client/src/app/demande-envoye/demande-envoye.component.ts
> +  }
Si on ne fait rien dans le ngOnInit, il n'est pas nécessaire de le mettre.

2022-05-09 08:37 UTC, patou commented on client/src/app/feedback-envoye/feedback-envoye.component.css
> +}
Il faut pas oublié de mettre un retour à la ligne à la fin des fichiers (github t'affiche un 
<img width="205" alt="image" src="https://user-images.githubusercontent.com/841858/167371844-ba0e15a0-fb58-4f40-bc06-902a45b90fdc.png">)

C'est une question pour git, si tu ajoute des nouvelles lignes, le diff git modifiera aussi cette ligne pour ajouter le retour à la ligne, donc tu aura une ligne de plus qui sera modifier (donc autant de conflit possible).

(Je ne met pas de commentaire sur tous les fichiers dans ce cas, il y en a plusieurs).

2022-05-09 08:37 UTC, patou commented on server/src/services/sendEmail.js
Vaut mieux de pas mettre 50 lignes vide ...
Une seule suffit.

2022-05-09 08:52 UTC, bnyat22 commented on client/src/app/demande-feedback/demande-feedback.component.css
> +    border-color: #ccc !important;
En fait c'était pour forcer changer les couleurs des bors des champs mais il se trouve que c'est pas nécessaire et n'est pas une bonne pratique, t'as raison

2022-05-09 08:55 UTC, bnyat22 commented on client/src/app/demande-feedback/demande-feedback.component.html
> +                <input  type="text" id="senderEmail" name="senderEmail"  [(ngModel)]="askFeedbackRequest.senderEmail" required class="col-6 form-control required" #senderEmail="ngModel" placeholder="
Je pensais puisque c'est un example précis on doit mettre un domain précis, d'accord je change

2022-05-09 09:54 UTC, bnyat22 commented on server/src/model/feedbackRequestTemplate.js
> +    }).join('');
d'accord je croyais que puisque c'est généré dans le coté de serveur il y aura pas de risques.

2022-05-09 09:56 UTC, patou commented on server/src/model/feedbackRequestTemplate.js
> +    }).join('');
Documente toi sur cette faille, là je peux mettre du code qui sera exécuté dans l'email.

2022-05-09 09:58 UTC, bnyat22 commented on server/src/model/feedbackRequestTemplate.js
> +    }).join('');
D'accord merci

2022-05-10 08:00 UTC, patou requested changes
Il y a toujours plusieurs commentaire sur la PR qui n'ont pas été traité.

2022-05-10 08:19 UTC, bnyat22 commented on server/src/services/sendEmail.js
> +   .catch(err => {return "Le feedback n'est pas envoyé, vérifier les données vérifier les données s'il vous plaît"})
Oups

2022-05-10 08:22 UTC, bnyat22 commented on client/src/app/demande-envoye/demande-envoye.component.spec.ts
> +  })
oui je vais revenir vers ces tests aujourd'hui ;-)

2022-05-10 08:22 UTC, merged

2022-05-11 08:25 UTC, bnyat22 commented on client/src/app/demande-feedback/demande-feedback.component.spec.ts
> +    ]
En fait je lance le eslint mais je sais pas pourquoi il me signale pas à ce genre de formatage notamment au coté client

2022-05-11 08:30 UTC, bnyat22 commented on client/src/app/demande-feedback/demande-feedback.component.ts
> +  sendFeedbackRequest(email:$email, senderEmail:$senderEmail, text:$text)
Oui justement dans la nouvelle PR j'ai créé un model askFeedback au lieu de passer tous ces paramètres notamment maintenant qu'il y a des autres paramètres en plus comme le nom de sender et receveur. Mais il y a encore des améliorations je vais le faire dans les prochaines PR.

2022-05-11 08:37 UTC, bnyat22 commented on client/src/app/demande-feedback/demande-feedback.component.ts
> +      data.data.sendFeedbackRequest==='Votre demande a bien été envoyé'? this.router.navigate(['/demandeEnvoye']):this.err=data.data.sendFeedbackRequest
En fait dans la root de réponse de graphql contient data. En dessous c'est une réponse de graphql, donc je suis obligé d'appeler data.data. Par contre d'accord oui un if else sera plus clair.
{
  "data": {
    "sendFeedbackRequest": "Votre demande a bien été envoyé"
  }
}

2022-05-11 08:44 UTC, bnyat22 commented on server/index.js
> +
Exactement, il y est plus

2022-05-11 08:46 UTC, bnyat22 commented on server/src/graphql/typeDefs.js
>      createMessage(email:String!,message:SendRequest!):String
yes ! merci

2022-05-11 12:38 UTC, patou commented on client/src/app/demande-feedback/demande-feedback.component.ts
> +      data.data.sendFeedbackRequest==='Votre demande a bien été envoyé'? this.router.navigate(['/demandeEnvoye']):this.err=data.data.sendFeedbackRequest
mais ta première variable data peut se nommer différemment pour éviter ce double data.data ?

2022-05-11 12:40 UTC, bnyat22 commented on client/src/app/demande-feedback/demande-feedback.component.ts
> +      data.data.sendFeedbackRequest==='Votre demande a bien été envoyé'? this.router.navigate(['/demandeEnvoye']):this.err=data.data.sendFeedbackRequest
oui peut-être je vais le nommer plutôt response