51 prefilling feedzback form
Zenika/feedzback pull request #52
Opened 2022-05-10 13:02 UTC by bnyat22

2022-05-11 13:50 UTC, patou requested changes

2022-05-11 13:50 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    }
Dans les urls il existe déjà un mécanisme pour passer des paramètres, ça s'appel des query params 
ça se trouve de la forme /formulaire/?nom=sdf&email=sdfsdf

Et c'est tellement extraordinaire, c'est que angular est même capable de les récupérer !
https://angular.io/guide/router#accessing-query-parameters-and-fragments

2022-05-11 13:50 UTC, patou commented on server/src/emailTemplate/askFeedbackModel.html
> +        <a href="http://localhost:4200/formulaire/<%=params%>">FeedZback</a>
Il faut que l'url soit remplacé par le host du server,
Car là ta branche ne fonctionne pas.

2022-05-11 13:50 UTC, patou commented on server/src/services/sendEmail.js
> +  }
C'est intéressant comme code, tu fait la même chose dans le if et le else ...

2022-05-11 13:54 UTC, bnyat22 commented on client/cypress/integration/formulaire-tests/formulaire.spec.js
> +      cy.get('#receverEmail').type('marie.mettrand@gmail.com')
ces des emails que j'ai inventé les noms mais t'as raison peut-être ils existent déjà

2022-05-11 14:02 UTC, bnyat22 commented on server/src/services/sendEmail.js
> +  }
:-) oui, non en fait dans le if je passe msgDev qui contient mon email et dans le else je passe msgProd. Parce-que Hugo a configuré mon email en mailgun pour tester en mode dev.

2022-05-11 14:02 UTC, patou commented on server/src/emailTemplate/askFeedbackModel.html
> +        <a href="http://localhost:4200/formulaire/<%=params%>">FeedZback</a>
C'est même de remettre, l'url ne devrait pas être en dur dans ton application.
C'est une variable d'environnement passer à ton application (a faire dans une autre PR).

2022-05-11 14:04 UTC, bnyat22 commented on server/src/emailTemplate/askFeedbackModel.html
> +        <a href="http://localhost:4200/formulaire/<%=params%>">FeedZback</a>
D'accord

2022-05-11 14:05 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    }
Ton serveur doit être capable d'encoder ta chaine pour en faire un query param.

2022-05-11 14:07 UTC, patou commented on server/src/services/sendEmail.js
> +  }
```suggestion
  res = await  myMailgun.messages().send((envi=='development') ? msgDev : msgProd)
     .then(()=> {return "Votre feedback a été envoyé!(Dev mode)"})
     .catch(err => {return "Le feedback n'est pas envoyé, vérifier les données s'il vous plaît"})
```

?

2022-05-11 14:10 UTC, bnyat22 commented on server/src/services/sendEmail.js
> +  }
oui génial! merci

2022-05-11 14:12 UTC, patou commented on server/src/services/sendEmail.js
>      from: 'bnyat.azizsharif@zenika.com',
Mais idem pour les autres email, laisser ton email perso dans le projet c'est pas génial.
Et comment va faire Vincent pour tester ?

2022-05-11 14:12 UTC, patou commented on server/src/services/sendEmail.js
> +  }
Ici tu construit deux objets qui ne sont pas utilisé tous les deux ...
```suggestion
const msg =   {
    to: sendRequest.receverEmail,
    from: sendRequest.email,
    subject:'FeedZback',
    html: template,
  }
  if (envi === 'developpement') {
    msg = {
      ...msg,
      to: 'bnyat.azizsharif@zenika.com',
      from: 'bnyat.azizsharif@zenika.com',
    };
  }
  
```
Tu peux avoir un code de ce style.

2022-05-11 14:14 UTC, bnyat22 commented on client/cypress/integration/formulaire-tests/formulaire.spec.js
> +      cy.get('#receverEmail').type('marie.mettrand@gmail.com')
si j'utilise par exemple pierre.henry@exemple.com au lieu de exemple@gmail.com

2022-05-11 14:15 UTC, bnyat22 commented on server/src/services/sendEmail.js
>      from: 'bnyat.azizsharif@zenika.com',
oui je dois demander à Hugo de configurer l'email feedzback plutôt que le mien

2022-05-11 14:17 UTC, patou commented on client/cypress/integration/formulaire-tests/formulaire.spec.js
> +      cy.get('#receverEmail').type('marie.mettrand@gmail.com')
Oui exemple.com est un domaine réservé pour l'utiliser dans la doc. Personne ne pourra récupérer ce domaine.

2022-05-12 08:35 UTC, bnyat22 commented on server/src/services/sendEmail.js
> +  }
stylé! merci

2022-05-12 08:58 UTC, patou commented on server/src/services/sendEmail.js
>    res = await  myMailgun.messages().send((envi=='development') ? msgDev : msgProd)
Du coup si tu fait la condition avant, plus besoin de la faire ici

2022-05-12 09:00 UTC, bnyat22 commented on server/src/services/sendEmail.js
>    res = await  myMailgun.messages().send((envi=='development') ? msgDev : msgProd)
oui je l'ai enlevé

2022-05-12 09:01 UTC, patou commented on client/src/app/formulaire/formulaire.component.html
> +                  <input type="email" name="email" id="email" class="col-md-12 form-control" id="email" [(ngModel)]="sendRequest!.email" required #email="ngModel" placeholder="Exemple: Pierre@exemple
```suggestion
                  <input type="email" name="email" id="email" class="col-md-12 form-control" id="email" [(ngModel)]="sendRequest!.email" required #email="ngModel" placeholder="Exemple: Pierre@exemple.com">
```
Que fait cet email à la fin ?

2022-05-12 09:02 UTC, patou commented on client/src/app/formulaire/formulaire.component.html
> +                 <input type="email" name="receverEmail" id="receverEmail" class="col-md-12 form-control" id="receverEmail" [(ngModel)]="sendRequest!.receverEmail" required #receverEmail="ngModel" pl
```suggestion
                 <input type="email" name="receverEmail" id="receverEmail" class="col-md-12 form-control" id="receverEmail" [(ngModel)]="sendRequest!.receverEmail" required #receverEmail="ngModel" placeholder="Exemple: Juliette@exemple.com">
```

2022-05-12 09:06 UTC, patou commented on client/src/app/formulaire/formulaire.component.spec.ts
> +
```suggestion
    email.setValue("pierre.pompidor@example.com")

    let receverEmail = component.feedbackForm.controls['receverEmail'];
    receverEmail.setValue("marie.mettrand@example.com")

```
En anglais c'est avec un a le example

2022-05-12 09:06 UTC, patou commented on client/src/app/formulaire/formulaire.component.spec.ts
> +
```suggestion
     email.setValue("pierre.henry@example.com")
      expect(email!.valid).toBeTruthy();
    }))

    it('champs Email Zenika de votre collègue est requis',waitForAsync(()=>{
      let senderEmail = component.feedbackForm.controls['receverEmail'];
       expect(senderEmail.valid).toBeFalsy();
     }))
     it('champs Email Zenika de votre collègue est valide quand il est remplis',waitForAsync(()=>{
       let senderEmail = component.feedbackForm.controls['receverEmail'];
       senderEmail.setValue("marie.mettrand@example.com")
        expect(senderEmail.valid).toBeTruthy();
      }))

```

2022-05-12 09:09 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    }
Quand je dis d'utiliser le paramMap, c'est d'avoir tous les parametres dans le query String sous la forme : 

/formulaire/?senderName=sdfsf&senderEmail=sdfqsdf@dsqf.fr[...]

Pour ainsi pouvoir faire un paramMap.get('senderName')

2022-05-12 09:09 UTC, bnyat22 commented on client/src/app/formulaire/formulaire.component.spec.ts
> +
Mais quand il s'agit d'expliquer on le fait pas en français? mais t'as raison en fait c'est un domain exemple pas l'explication.

2022-05-12 09:12 UTC, bnyat22 commented on client/src/app/formulaire/formulaire.component.ts
> +    }
mais dans ce cas là on doit mettre dans le route path de formulaire /:senderName/:name/:receverName/:receverEmail
c'est pas un peu long?

2022-05-12 09:21 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    }
bah non ça sera en mode queryString 
/formulaire/?senderName=dfsd&senderEmail=qdfqd@qsdf.fr[...]

2022-05-12 12:48 UTC, bnyat22 commented on client/src/app/formulaire/formulaire.component.ts
> +    }
ça devrait être bon, en plus avec URLSearchParams, on peut les envoyer tous ensemble

2022-05-13 08:09 UTC, patou commented on client/cypress/integration/formulaire-tests/formulaire.spec.js
> +      cy.get('#receverEmail').type('marie.mettrand@gmail.com')
Je vois toujours des gmail.com

2022-05-13 08:09 UTC, patou commented on client/src/app/formulaire/formulaire.component.ts
> +    }
```suggestion
    const query = this.activateRouter.snapshot.queryParamMap;
    this.sendRequest = {
        senderName: query.get('senderName'),
        senderEmail: query.get('senderEmail'),
        receverName: query.get('receverName'),
        receverEmail: query.get('receverEmail'),
    };
```

2022-05-13 08:09 UTC, patou commented on server/src/emailTemplate/askFeedbackModel.html
> +        <a href="<%=urlClientForm%>;params=<%=params%>">FeedZback</a>
c'est quoi ce ;params ?

2022-05-13 08:20 UTC, bnyat22 commented on server/src/emailTemplate/askFeedbackModel.html
> +        <a href="<%=urlClientForm%>;params=<%=params%>">FeedZback</a>
c'était avant je l'avais oublié de pushé

2022-05-13 08:21 UTC, bnyat22 commented on client/cypress/integration/formulaire-tests/formulaire.spec.js
> +      cy.get('#receverEmail').type('marie.mettrand@gmail.com')
oui parc-que j'avais commit mais oublié de faire push

2022-05-13 08:33 UTC, patou commented on server/src/emailTemplate/askFeedbackModel.html
> +        <a href="<%=urlClientForm%>;params=<%=params%>">FeedZback</a>
Ok !

2022-05-16 07:26 UTC, merged